export const STORAGE_KEY_APPLIED_LIST = 'appliedList'
export const STORAGE_KEY_APPLIED_LIST_LENGTH = 'appliedListLength'
export const STORAGE_KEY_APPLIED_LAST_SYNC_DATETIME = 'lastSyncDatetime'
export const STORAGE_KEY_APPLIED_TRIE = 'appliedTrie'
export const SYNC_STORAGE_KEY_SHEET_ID = 'sheetId'
